name: Daily GTFS Fetch

on:
  # מגדיר את התזמון הלילי באמצעות Cron.
  # הדוגמה: הרצה יומית בשעה 03:00 UTC (בקיץ זה 06:00 בבוקר בישראל, בחורף 05:00)
  schedule:
    - cron: '0 3 * * *'
  # מאפשר הרצה ידנית מהממשק הגרפי
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        # מוריד את הקוד של הרפוזיטורי (כולל ה-download_gtfs.py)
        uses: actions/checkout@v4
        with:
          # זה חיוני כדי לאפשר לקוד לבצע Commit חדש
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        # הגדרת סביבת Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        # התקנת ספריית requests הנדרשת
        run: pip install requests

      - name: Run GTFS Download Script
        # מריץ את סקריפט הפייתון
        id: run_script
        run: python download_gtfs.py
      
      - name: Commit files if changed
        # משתמש ב-Action של צד שלישי לביצוע Add ו-Commit
        # זה חוסך לנו כתיבת קוד Git בפייתון
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.run_script.outputs.commit_message }}
          # רק הקובץ gtfs.zip נשמר בגרסאות
          files: gtfs.zip
          # מאפשר ריצה אוטומטית גם אם אין שינויים
          commit_options: '--allow-empty'
